# Generated by Django 5.2.8 on 2025-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الفيديو', max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, help_text='وصف الفيديو (اختياري)', null=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='videos/', verbose_name='ملف الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='صورة مصغرة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحميل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('views', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'فيديوهات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
